// <auto-generated />
namespace MyRecords.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SenderReceiver3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SenderReceiver3));
        
        string IMigrationMetadata.Id
        {
            get { return "201504181312060_SenderReceiver3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
