// <auto-generated />
namespace MyRecords.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SenderReceiver2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SenderReceiver2));
        
        string IMigrationMetadata.Id
        {
            get { return "201504181308084_SenderReceiver2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
