// <auto-generated />
namespace MyRecords.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DateCreatedArtist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateCreatedArtist));
        
        string IMigrationMetadata.Id
        {
            get { return "201504182331451_DateCreatedArtist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
